export default {
  react: { icon: "", mainColor: "", isChose: false },
  学习: { icon: "", mainColor: "", isChose: false },
  style: { icon: "", mainColor: "", isChose: false },
  娱乐: { icon: "", mainColor: "", isChose: false },
  "react native": { icon: "", mainColor: "", isChose: false },
  TensorFlow: { icon: "", mainColor: "", isChose: false },
  Ai: { icon: "", mainColor: "", isChose: false },
  github: { icon: "", mainColor: "", isChose: false },
  code: { icon: "", mainColor: "", isChose: false },
  javascript: { icon: "", mainColor: "", isChose: false },
  "stack overflow": { icon: "", mainColor: "", isChose: false },
  mail: { icon: "", mainColor: "", isChose: false },
  "google product": { icon: "", mainColor: "", isChose: false },
  translate: { icon: "", mainColor: "", isChose: false },
  "baidu product": { icon: "", mainColor: "", isChose: false },
  note: { icon: "", mainColor: "", isChose: false },
  record: { icon: "", mainColor: "", isChose: false },
  "chrome tool": { icon: "", mainColor: "", isChose: false },
  design: { icon: "", mainColor: "", isChose: false },
  color: { icon: "", mainColor: "", isChose: false },
  "cloud service": { icon: "", mainColor: "", isChose: false },
  小程序: { icon: "", mainColor: "", isChose: false },
};
